/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0f0602",
        "on-primary": "#ffffff",
        "primary-container": "#2a1d15",
        "on-primary-container": "#988378",
        "primary-fixed": "#f6ded1",
        "primary-fixed-dim": "#d9c2b5",
        "on-primary-fixed": "#251911",
        "on-primary-fixed-variant": "#54433a",
        "secondary": "#825511",
        "on-secondary": "#ffffff",
        "secondary-container": "#fec074",
        "on-secondary-container": "#794d08",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#f8bb70",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary": "#170300",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#400f00",
        "on-tertiary-container": "#cd6d4c",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#7a2f12",
        "surface": "#fdf9f3",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#4e4540",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3ed",
        "surface-container": "#f1ede7",
        "surface-container-high": "#ebe8e2",
        "surface-container-highest": "#e6e2dc",
        "surface-dim": "#dddad4",
        "surface-bright": "#fdf9f3",
        "surface-variant": "#e6e2dc",
        "surface-tint": "#6d5b51",
        "background": "#fdf9f3",
        "on-background": "#1c1c18",
        "outline": "#80756f",
        "outline-variant": "#d2c4bd",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f4f0ea",
        "inverse-primary": "#d9c2b5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
